sugarcube-2:
  macros:
    playtime:
      name: playtime
    cont:
      name: cont-macro-ignore
    correct:
      name: correct
    fadein:
      container: true
      name: fadein
    date:
      name: date
    knight-stats:
      name: knight-stats
    repeat:
      name: repeat
    gorandom:
      name: gorandom
    storyicons:
      name: storyicons
    wrong:
      name: wrong